packages:
  - 'tools/*'
  - 'packages/*'
  - 'docs/*'

catalog:
  '@microsoft/api-extractor': ^7.49.2
  '@types/jest': ^29.5.14
  '@types/node': ^22.13.1
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3
  '@nx/devkit': ^20.4.6
  '@nx/eslint-plugin': ^20.4.6
  '@nx/eslint': ^20.4.6
  '@nx/jest': ^20.4.6
  '@nx/js': ^20.4.6
  '@nx/plugin': ^20.4.6
  '@nx/react': ^20.4.6
  '@nx/workspace': ^20.4.6
  '@storm-software/config': latest
  '@storm-software/config-tools': latest
  '@storm-software/cspell': latest
  '@storm-software/git-tools': latest
  '@storm-software/linting-tools': latest
  '@storm-software/eslint': latest
  '@storm-software/prettier': latest
  '@storm-software/unbuild': latest
  '@storm-software/untyped': latest
  '@storm-software/testing-tools': latest
  '@storm-software/tsconfig': latest
  '@storm-software/workspace-tools': latest
  '@storm-software/markdownlint': latest
  '@swc-node/register': ^1.10.9
  '@swc/core': ^1.10.14
  '@swc/wasm': ^1.10.14
  '@swc/helpers': ^0.5.15
  eslint: ^9.20.0
  nx: ^20.4.6
  jest: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  jest-environment-node: ^29.7.0
  tsup: ^8.3.5
  tsdown: ^0.5.8
  tslib: ^2.8.1
  copyfiles: ^2.4.1
  rimraf: ^6.0.1
  react: ^19.0.0
  react-dom: ^19.0.0
  react-native: ^0.77.0
  typescript: ^5.6.2
  esbuild: ^0.25.0
  unbuild: ^3.3.1
  defu: ^6.1.4
  jiti: ^2.4.2
