onlyBuiltDependencies:
  - "@swc/core"
  - core-js
  - esbuild
  - lefthook
  - nx
packages:
  - "tools/*"
  - "packages/*"

catalog:
  "@antfu/install-pkg": ^1.0.0
  "@antfu/ni": ^23.3.1
  "@dotenvx/dotenvx": 1.39.1
  "@js-temporal/polyfill": ^0.5.1
  "@ls-lint/ls-lint": ^2.3.0
  "@microsoft/api-extractor": ^7.52.3
  "@prisma/client": ^6.6.0
  "@prisma/generator-helper": ^6.6.0
  "@prisma/internals": ^6.6.0
  "@prisma/prisma-schema-wasm": ^6.6.0-53.f676762280b54cd07c770017ed3711ddde35f37a
  "@tanstack/react-query": ^5.72.2
  "@tanstack/react-query-devtools": ^5.72.2
  "@taplo/cli": ^0.7.0
  "@trpc/client": next
  "@trpc/next": next
  "@trpc/server": next
  "@trpc/tanstack-react-query": next
  "@types/figlet": ^1.7.0
  "@types/jest": ^29.5.14
  "@types/node": ^22.14.0
  "@types/pluralize": ^0.0.33
  "@types/react": ^19.0.12
  "@types/react-dom": ^19.0.4
  "@nx/devkit": ^20.7.2
  "@nx/eslint-plugin": ^20.7.2
  "@nx/eslint": ^20.7.2
  "@nx/jest": ^20.7.2
  "@nx/js": ^20.7.2
  "@nx/plugin": ^20.7.2
  "@nx/react": ^20.7.2
  "@nx/workspace": ^20.7.2
  "@storm-software/build-tools": latest
  "@storm-software/config": latest
  "@storm-software/config-tools": latest
  "@storm-software/cspell": latest
  "@storm-software/git-tools": latest
  "@storm-software/linting-tools": latest
  "@storm-software/eslint": latest
  "@storm-software/esbuild": latest
  "@storm-software/prettier": latest
  "@storm-software/unbuild": latest
  "@storm-software/untyped": latest
  "@storm-software/testing-tools": latest
  "@storm-software/tsconfig": latest
  "@storm-software/workspace-tools": latest
  "@storm-software/markdownlint": latest
  "@swc-node/register": ^1.10.10
  "@swc/core": ^1.11.20
  "@swc/wasm": ^1.11.20
  "@swc/helpers": ^0.5.17
  "@types/react-native": 0.73.0
  "@types/semver": ^7.7.0
  "@zkochan/js-yaml": ^0.0.7
  buffer: 6.0.3
  chalk: ^5.4.1
  consola: ^3.4.2
  eslint: ^9.24.0
  eslint-flat-config-utils: ^2.0.1
  execa: ^9.5.2
  figlet: ^1.8.0
  glob: ^11.0.1
  js-xxhash: ^4.0.0
  jsonc-parser: 3.3.1
  knip: 5.50.2
  lefthook: ^1.11.9
  lines-and-columns: 2.0.4
  ls-lint: ^0.1.2
  markdownlint-cli2: ^0.17.2
  mlly: 1.7.4
  nanotar: ^0.2.0
  nx: ^20.7.2
  jest: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  jest-environment-node: ^29.7.0
  parenthesis: ^3.1.8
  pluralize: ^8.0.0
  prettier: ^3.5.3
  semver: 7.7.1
  server-only: ^0.0.1
  sherif: 1.5.0
  superjson: 2.2.2
  terminal-link: ^3.0.0
  tinyexec: ^0.3.2
  ts-jest: 29.3.1
  ts-morph: ^25.0.1
  ts-node: 10.9.2
  tsup: ^8.3.5
  tsdown: ^0.6.10
  tslib: ^2.8.1
  copyfiles: ^2.4.1
  rimraf: ^6.0.1
  react: ^19.1.0
  react-dom: ^19.1.0
  react-native: ^0.77.0
  typescript: ~5.7.3
  esbuild: ^0.25.2
  ufo: 1.6.1
  unbuild: ^3.5.0
  defu: ^6.1.4
  jiti: ^2.4.2
  verdaccio: 5.33.0
  zod: ^3.24.2
  zx: ^8.5.2

overrides:
  "@stryke/cli": workspace:*
  "@stryke/convert": workspace:*
  "@stryke/env": workspace:*
  "@stryke/fs": workspace:*
  "@stryke/hash": workspace:*
  "@stryke/helpers": workspace:*
  "@stryke/hooks": workspace:*
  "@stryke/http": workspace:*
  "@stryke/json": workspace:*
  "@stryke/path": workspace:*
  "@stryke/prisma-better-auth-generator": workspace:*
  "@stryke/prisma-trpc-generator": workspace:*
  "@stryke/string-format": workspace:*
  "@stryke/trpc-next": workspace:*
  "@stryke/type-checks": workspace:*
  "@stryke/types": workspace:*
  "@stryke/unique-id": workspace:*
  cookie: ">=0.7.0"
  debug: ">=4.4.0"
  follow-redirects: ">=1.15.9"
  got: ">=14.4.5"
  ip: ">=2.0.1"
  loader-utils: ">=3.3.1"
  markdown-it: ">=14.1.0"
  micromatch: ">=4.0.8"
  next: ">=13.4.20-canary.13"
  node-fetch: ">=3.3.2"
  nth-check: ">=2.1.1"
  parse-path: ">=7.0.0"
  parse-url: ">=9.2.0"
  path-to-regexp: ">=0.1.12"
  postcss: ">=8.5.1"
  shell-quote: ">=1.8.2"
  simple-git: ">=3.27.0"
