packages:
  - "tools/*"
  - "packages/*"
  - "docs/*"

catalog:
  "@microsoft/api-extractor": "^7.48.1"
  "@types/jest": "29.5.13"
  "@types/react": "npm:types-react@rc"
  "@types/react-dom": "npm:types-react-dom@rc"
  "@types/node": "^22.10.2"
  "@nx/devkit": "^20.3.0"
  "@nx/eslint-plugin": "^20.3.0"
  "@nx/jest": "^20.3.0"
  "@nx/js": "^20.3.0"
  "@nx/plugin": "^20.3.0"
  "@nx/react": "^20.3.0"
  "@nx/workspace": "^20.3.0"
  "@storm-software/config": "latest"
  "@storm-software/config-tools": "latest"
  "@storm-software/cspell": "latest"
  "@storm-software/git-tools": "latest"
  "@storm-software/linting-tools": "latest"
  "@storm-software/eslint": "latest"
  "@storm-software/prettier": "latest"
  "@storm-software/unbuild": "latest"
  "@storm-software/untyped": "latest"
  "@storm-software/testing-tools": "latest"
  "@storm-software/tsconfig": "latest"
  "@storm-software/workspace-tools": "latest"
  "@swc-node/register": "^1.10.9"
  "@swc/core": "^1.7.26"
  "@swc/wasm": "^1.10.1"
  "@swc/helpers": "^0.5.13"
  "eslint": "9.12.0"
  "nx": "^20.3.0"
  "prettier": "^3.4.2"
  "jest": "29.7.0"
  "jest-environment-jsdom": "29.7.0"
  "jest-environment-node": "29.7.0"
  "react": "19.0.0-rc-f6cce072-20240723"
  "react-dom": "19.0.0-rc-f6cce072-20240723"
  "react-native": "0.75.4"
  "tsup": "^8.3.5"
  "tsdown": "^0.5.3"
  "copyfiles": "^2.4.1"
  "rimraf": "^6.0.1"
  "typescript": "^5.6.2"
  "esbuild": "^0.24.0"
  "unbuild": "^3.3.0"
  "defu": "6.1.4"
  "jiti": "2.4.2"
