/* -------------------------------------------------------------------

                       ⚡ Storm Software - Stryke

 This code was released as part of the Stryke project. Stryke
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/stryke.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/stryke
 Documentation:            https://docs.stormsoftware.com/projects/stryke
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { canonicalJson } from "@stryke/json/canonical";
import { base64UrlDecode, base64UrlEncode } from "./base-64";

/**
 * Parameters for Ed25519 key generation and signing in Cloudflare Workers. This interface defines the algorithm name and named curve used for Ed25519 operations in the Cloudflare Workers environment. The `name` and `namedCurve` properties are set to "NODE-ED25519" to indicate that these parameters are specific to Cloudflare Workers' implementation of Ed25519, which is not compatible with standard Web Crypto API Ed25519 implementations in other environments.
 */
export interface Ed25519Params {
  name: "NODE-ED25519";
  namedCurve: "NODE-ED25519";
}

/**
 * Represents an Ed25519 key pair with a public key and a private key, both of which are CryptoKey objects. This interface is used to define the structure of the key pair generated by the `generateSigningKeyPair` function, where the `publicKey` is used for signature verification and the `privateKey` is used for signing operations. The keys are generated using Cloudflare Workers' `NODE-ED25519` algorithm parameters, which are specific to Cloudflare Workers' implementation of Ed25519 and are not compatible with standard Web Crypto API Ed25519 implementations in other environments.
 */
export interface Ed25519KeyPair {
  publicKey: CryptoKey;
  privateKey: CryptoKey;
}

/**
 * Generates an Ed25519 key pair using Cloudflare Workers' `NODE-ED25519` algorithm and returns the public key as a base64 string, the private key as a JWK object, and a key ID derived from the public key. The private key is returned as a JWK for compatibility with Web Crypto API operations.
 *
 * @remarks
 * This function uses Cloudflare Workers' `NODE-ED25519` algorithm parameters, which are specific to Cloudflare Workers' implementation of Ed25519. The returned key pair is structured as follows:
 * - The `publicKey` is returned as a base64url-encoded string of the raw public key bytes (the 'x' parameter from the JWK).
 * - The `privateKeyJwk` is returned as a JWK object containing the private key parameters, which can be used for signing operations with the Web Crypto API.
 * - The `keyId` is generated by hashing the raw public key bytes and taking the first 4 bytes of the hash, encoded as a hex string prefixed with "ed25519:". This provides a unique identifier for the key pair based on its public key.
 *
 * This function is not compatible with standard Web Crypto API Ed25519 implementations in other environments. The legacy function `generateSigningKeyPairLegacy` is also available for backwards compatibility, which returns the private key as a JSON stringified JWK. However, it is recommended to use this structured version for new code.
 *
 * @returns An object containing the `publicKey` as a base64 string, the `privateKeyJwk` as a JWK object, and a `keyId` derived from the public key.
 * @throws {@link DOMException} If key generation or export fails in the Web Crypto API.
 */
export async function generateSigningKeyPair(): Promise<{
  publicKey: string;
  privateKeyJwk: JsonWebKey;
  keyId: string;
}> {
  // Generate Ed25519 key pair using Cloudflare Workers' native support
  const keyPair = await crypto.subtle.generateKey(
    { name: "NODE-ED25519", namedCurve: "NODE-ED25519" } as Ed25519Params,
    true, // extractable
    ["sign", "verify"]
  );

  // Export the public key as JWK to get the raw key bytes
  const publicKeyJwk = await crypto.subtle.exportKey("jwk", keyPair.publicKey);
  const privateKeyJwk = await crypto.subtle.exportKey(
    "jwk",
    keyPair.privateKey
  );

  // Get raw public key bytes from the JWK 'x' parameter
  const publicKeyBytes = base64UrlDecode(publicKeyJwk.x!);

  // Generate key ID from first 4 bytes of public key hash (for uniqueness)
  const keyIdHash = new Uint8Array(
    await crypto.subtle.digest("SHA-256", publicKeyBytes as BufferSource)
  ).slice(0, 4);
  const keyId = `ed25519:${Array.from(keyIdHash)
    .map(b => b.toString(16).padStart(2, "0"))
    .join("")}`;

  return {
    publicKey: base64UrlEncode(publicKeyBytes),
    privateKeyJwk,
    keyId
  };
}

/**
 * Generates an Ed25519 key pair and returns the public key as a base64 string, the private key as a JSON stringified JWK, and a key ID derived from the public key. The private key is returned in a legacy format for compatibility with existing code that expects a JSON string.
 *
 * @remarks
 * Legacy function for backwards compatibility during migration. Returns the old format but with a proper key.
 *
 * @deprecated Use `generateSigningKeyPair` instead, which returns a structured key object and separate key ID. This legacy function is retained for backwards compatibility but may be removed in future releases.
 *
 * @returns An object containing the `publicKey` as a base64 string, the `privateKey` as a JSON stringified JWK, and a `keyId` derived from the public key.
 * @throws {@link SyntaxError} If the generated private key cannot be stringified to JSON (should not occur under normal circumstances).
 */
export async function generateSigningKeyPairLegacy(): Promise<{
  publicKey: string;
  privateKey: string;
  keyId: string;
}> {
  const { publicKey, privateKeyJwk, keyId } = await generateSigningKeyPair();

  return {
    publicKey,
    privateKey: JSON.stringify(privateKeyJwk),
    keyId
  };
}

/**
 * Creates and attaches an [Ed25519 signature](https://matrix.org/docs/spec/client_server/latest#signing-json-objects) for a JSON object using [Matrix-style](https://matrix.org/docs/spec/client_server/latest#signing-json-objects) signing rules.
 *
 * @see https://matrix.org/docs/spec/client_server/latest#signing-json-objects
 *
 * @remarks
 * - Signature output is encoded as un-padded base64url.
 * - The original `obj` is not mutated.
 * - Uses `NODE-ED25519` algorithm parameters for key import/sign operations.
 *
 * The function canonicalizes a copy of the input object after removing the `signatures`
 * and `unsigned` properties, signs that canonical JSON payload with the provided private key,
 * and returns a new object with the generated signature merged into `obj.signatures`.
 *
 * Existing signatures are preserved, including other keys under the same `serverName`.
 *
 * @param obj - The JSON object to sign.
 * @param serverName - The signing entity name used as the top-level key in `signatures`.
 * @param keyId - The key identifier used under `signatures[serverName]`.
 * @param privateKeyJwk - The Ed25519 private key as a JWK object, or a JSON stringified JWK (legacy compatibility).
 * @returns A new object containing all original fields plus an updated `signatures` map with the new signature.
 * @throws {@link SyntaxError} If `privateKeyJwk` is a string that is not valid JSON.
 * @throws {@link DOMException} If key import or signing fails in the Web Crypto API.
 */
export async function signJson(
  obj: Record<string, unknown>,
  serverName: string,
  keyId: string,
  privateKeyJwk: JsonWebKey | string
): Promise<Record<string, unknown>> {
  // Parse JWK if passed as string (for backwards compatibility)
  const jwk: JsonWebKey =
    typeof privateKeyJwk === "string"
      ? JSON.parse(privateKeyJwk)
      : privateKeyJwk;

  // Remove signatures and unsigned before signing (per Matrix spec)
  const toSign = { ...obj };
  delete toSign.signatures;
  delete toSign.unsigned;

  // Import the private key
  const privateKey = await crypto.subtle.importKey(
    "jwk",
    jwk,
    { name: "NODE-ED25519", namedCurve: "NODE-ED25519" },
    false,
    ["sign"]
  );

  // Get canonical JSON representation
  const canonical = canonicalJson(toSign);

  // Sign the canonical JSON
  const signatureBytes = await crypto.subtle.sign(
    { name: "NODE-ED25519" },
    privateKey,
    new TextEncoder().encode(canonical)
  );

  // Encode signature as un-padded base64
  const signatureB64 = base64UrlEncode(new Uint8Array(signatureBytes));

  // Merge with existing signatures if present
  const existingSignatures =
    (obj.signatures as Record<string, Record<string, string>>) ?? {};

  return {
    ...obj,
    signatures: {
      ...existingSignatures,
      [serverName]: {
        ...(existingSignatures[serverName] ?? {}),
        [keyId]: signatureB64
      }
    }
  };
}

/**
 * Verifies an Ed25519 signature on a JSON object using [Matrix-style signing rules](https://matrix.org/docs/spec/client_server/latest#signing-json-objects). The function extracts the relevant signature from the `signatures` property of the input object, removes the `signatures` and `unsigned` properties to create a canonical JSON payload, and then verifies the signature against the provided public key. The public key is expected to be a base64url-encoded string of the raw public key bytes (the 'x' parameter from the JWK). The function returns `true` if the signature is valid and `false` otherwise. Any errors during the verification process are caught and logged, with a return value of `false` in case of failure.
 *
 * @see https://matrix.org/docs/spec/client_server/latest#signing-json-objects
 *
 * @remarks
 * - Signature input is expected to be un-padded base64url.
 * - The original `obj` is not mutated.
 * - Uses `NODE-ED25519` algorithm parameters for key import/verify operations.
 * - The function does not throw on verification failure; it returns `false` instead. Errors during key import or verification are logged to the console for debugging purposes.
 *
 * @param obj - The JSON object containing the signature to verify.
 * @param serverName - The signing entity name used as the top-level key in `signatures`.
 * @param keyId - The key identifier used under `signatures[serverName]` to locate the specific signature to verify.
 * @param publicKeyB64 - The Ed25519 public key as a base64url-encoded string of the raw public key bytes (the 'x' parameter from the JWK).
 * @returns A boolean indicating whether the signature is valid (`true`) or not (`false`). Returns `false` if the signature is missing, invalid, or if any errors occur during the verification process.
 */
export async function verifySignature(
  obj: Record<string, unknown>,
  serverName: string,
  keyId: string,
  publicKeyB64: string
): Promise<boolean> {
  try {
    // Get the signature
    const signatures = obj.signatures as
      | Record<string, Record<string, string>>
      | undefined;
    const signature = signatures?.[serverName]?.[keyId];
    if (!signature) {
      return false;
    }

    // Remove signatures and unsigned before verifying
    const toVerify = { ...obj };
    delete toVerify.signatures;
    delete toVerify.unsigned;

    // Decode the public key
    const publicKeyBytes = base64UrlDecode(publicKeyB64);

    // Import the public key
    const publicKey = await crypto.subtle.importKey(
      "raw",
      publicKeyBytes as BufferSource,
      { name: "NODE-ED25519", namedCurve: "NODE-ED25519" },
      false,
      ["verify"]
    );

    // Decode the signature
    const signatureBytes = base64UrlDecode(signature);

    // Get canonical JSON
    const canonical = canonicalJson(toVerify);

    // Verify the signature
    return await crypto.subtle.verify(
      { name: "NODE-ED25519" },
      publicKey,
      signatureBytes as BufferSource,
      new TextEncoder().encode(canonical)
    );
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error("Signature verification failed:", error);
    return false;
  }
}
