/* eslint-disable */
// biome-ignore lint: disable
// Generated by Storm Stack
// Note: Do not edit this file manually - it will be overwritten automatically
import * as $ from "@stryke/capnp";
export const _capnpFileId = BigInt("0xbdf87d7bb8304e82");
