/* eslint-disable */
// biome-ignore lint: disable
// Generated by storm-capnpc
// Note: Do not edit this file manually - it will be overwritten automatically
export const _capnpFileId = BigInt("0xbdf87d7bb8304e82");
