/* eslint-disable */
// biome-ignore lint: disable
// Generated by storm-capnpc
// Note: Do not edit this file manually - it will be overwritten automatically
export const _capnpFileId = BigInt("0xe37ded525a68a7c9");
